### PR TITLE
Run `npm run fix`

### PR DESCRIPTION
**Pull request by christianbundy**
Problem: The linter was throwing lots of un-fun errors.

Solution: `npm run fix` to resolve them.

---

cc: @zicmama once you merge this then I can merge your PR into fraction/oasis :tada:

### CODE REVIEW

**Comment by zicmama** [comment]
```
> @fraction/oasis@2.15.0 fix /home/fred/workspace/oasis
> common-good fix

sh: 1: common-good: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @fraction/oasis@2.15.0 fix: `common-good fix`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @fraction/oasis@2.15.0 fix script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fred/.npm/_logs/2020-04-13T16_30_27_377Z-debug.log
```

**Comment by zicmama** [comment]
cat /home/fred/.npm/_logs/2020-04-13T16_30_27_377Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/fred/.nvm/versions/node/v12.16.1/bin/node',
1 verbose cli   '/home/fred/.nvm/versions/node/v12.16.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'fix'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prefix', 'fix', 'postfix' ]
5 info lifecycle @fraction/oasis@2.15.0~prefix: @fraction/oasis@2.15.0
6 info lifecycle @fraction/oasis@2.15.0~fix: @fraction/oasis@2.15.0
7 verbose lifecycle @fraction/oasis@2.15.0~fix: unsafe-perm in lifecycle true
8 verbose lifecycle @fraction/oasis@2.15.0~fix: PATH: /home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/fred/workspace/oasis/node_modules/.bin:/home/fred/.nvm/versions/node/v12.16.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/fred/.local/bin:/usr/local/go/bin
9 verbose lifecycle @fraction/oasis@2.15.0~fix: CWD: /home/fred/workspace/oasis
10 silly lifecycle @fraction/oasis@2.15.0~fix: Args: [ '-c', 'common-good fix' ]
11 info lifecycle @fraction/oasis@2.15.0~fix: Failed to exec fix script
12 verbose stack Error: @fraction/oasis@2.15.0 fix: `common-good fix`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/home/fred/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:311:20)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
13 verbose pkgid @fraction/oasis@2.15.0
14 verbose cwd /home/fred/workspace/oasis
15 verbose Linux 5.3.0-46-generic
16 verbose argv "/home/fred/.nvm/versions/node/v12.16.1/bin/node" "/home/fred/.nvm/versions/node/v12.16.1/bin/npm" "run" "fix"
17 verbose node v12.16.1
18 verbose npm  v6.13.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error @fraction/oasis@2.15.0 fix: `common-good fix`
23 error spawn ENOENT
24 error Failed at the @fraction/oasis@2.15.0 fix script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

I start using git or npm a few weeks ago

**Comment by christianbundy** [comment]
Sorry, you just need to hit "Merge pull request" on this page to apply my patch to your branch. You only need to run `npm run fix` if you're *not* going to merge this pull request.

If you'd like to run it yourself, I think you just need `npm install` before `npm run fix`

**Comment by zicmama** [comment]
ok I made as you said. accept Merge here, git pull on my PC
npm install (is this installing oasis or npm?)
npm run fix
```

> @fraction/oasis@2.15.0 fix /home/fred/workspace/oasis
> common-good fix

=> prettier --write .
.cspell.json 36ms
.github/ISSUE_TEMPLATE.md 23ms
.github/PULL_REQUEST_TEMPLATE.md 4ms
.travis.yml 37ms
contrib/install-systemd-service.js 33ms
docs/architecture.md 73ms
docs/blob-security.md 32ms
docs/CHANGELOG.md 19ms
docs/code-of-conduct.md 48ms
docs/configuring.md 20ms
docs/contract.md 131ms
docs/contributing.md 23ms
docs/install.md 16ms
docs/maintaining.md 10ms
docs/security.md 15ms
docs/translating.md 7ms
docs/with-docker.md 4ms
docs/with-systemd.md 7ms
docs/with-termux.md 9ms
package-lock.json 463ms
package.json 13ms
README.md 46ms
src/assets/highlight.css 44ms
src/assets/style.css 172ms
src/cli.js 38ms
src/http.js 54ms
src/index.js 262ms
src/models.js 296ms
src/ssb.js 72ms
src/views/i18n.js 104ms
src/views/index.js 160ms
src/views/markdown.js 10ms
test/basic.js 17ms
=> stylelint --fix --allow-empty-input **/*.css
=> eslint -c /home/fred/workspace/oasis/node_modules/common-good/.eslintrc.js --fix **/*.{js,ts}

```

sorry for my dump questions... I don't' figure out yet what all the command I type are really making

**Comment by christianbundy** [comment]
No problem! Before you make a commit, you can run `npm install && npm run fix` to make sure the code is consistently indented and such. 

`npm install` downloads dependencies for the Oasis project.

**Pull request merged**
